services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\ComposerReactions\:
    resource: "../Classes/*"
    exclude: "../Classes/Domain/Model/*"

  WapplerSystems\ComposerReactions\Command\ComposerUpdateCommand:
    tags:
      - name: console.command
        command: "composer:update"
